accounts/urls.py
from django.urls import path

from .views import home_view, login_attempt, register_attempt

app_name = 'accounts'
urlpatterns = [
    path('', home_view, name='home'),
    path('login/', login_attempt, name='login_attempt'),
    path('register/', register_attempt, name='register_attempt'),
]

django_email_phone_verification/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
import random

from django.db import models
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin


def set_username(sender, instance, **kwargs):
    if not instance.username:
        username = (instance.first_name + "." + instance.last_name).lower()
        counter = 1
        while User.objects.filter(username=username):
            username += str(counter)
            counter += 1
        instance.username = username


def generate_code():
    number_list = [x for x in range(10)]
    code_items = []

    for i in range(6):
        num = random.choice(number_list)
        code_items.append(num)
    code_string = "".join(str(item) for item in code_items)
    return code_string


class CustomUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None):
        if not email:
            raise ValueError("User must have an email address")
        if not first_name:
            raise ValueError("User must have first name")
        if not last_name:
            raise ValueError("User must have last name")
        if not password:
            raise ValueError("User must have a password")

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staffuser(self, email, first_name, last_name, password=None):
        user = self.create_user(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            password=password
        )
        user.is_staff = True
        user.save(using=self._db)
        return user

    def create_superuser(self, email, first_name, last_name, password=None):
        user = self.create_user(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            password=password
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(verbose_name='email', unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    # EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class UserDetail(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_verified_email = models.BooleanField(default=False)
    auth_token_email = models.CharField(max_length=6, blank=True)

    phone_number = models.CharField(max_length=14, null=True, blank=True)
    is_verified_phone = models.BooleanField(default=False)
    auth_token_phone = models.CharField(max_length=6, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        if self.user.email:
            self.auth_token_email = generate_code()
        if self.phone_number:
            self.auth_token_phone = generate_code()

        print(self.auth_token_phone)
        print(self.auth_token_email)

        super().save(*args, **kwargs)


models.signals.pre_save.connect(set_username, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model, authenticate

User = get_user_model()


class UserRegisterModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password', ]


class UserLoginModelForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'password', ]

    def clean(self):
        if self.is_valid():
            email = self.cleaned_data['email']
            password = self.cleaned_data['password']
            if not authenticate(email=email, password=password):
                raise forms.ValidationError("Email or password incorrect!")

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth import get_user_model

from .forms import UserRegisterModelForm, UserLoginModelForm

User = get_user_model()


def home_view(request):
    if not request.user.is_authenticated:
        return redirect('accounts:login_attempt')
    context = {
        'title': 'Home'
    }
    return render(request, 'accounts/home.html', context)


def register_attempt(request):
    if request.POST:
        form = UserRegisterModelForm(request.POST)
        if form.is_valid():
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']
            email = request.POST['email']
            password = request.POST['password']
            user = User.objects.create(first_name=first_name,
                                       last_name=last_name,
                                       email=email)
            user.set_password(password)
            user.save()
            return redirect('accounts:login_attempt')
    context = {
        'title': 'Register'
    }
    return render(request, 'accounts/register.html', context)


def login_attempt(request):
    context = {}
    if request.POST:
        form = UserLoginModelForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                return redirect('accounts:home')
    else:
        form = UserLoginModelForm()
    context = {
        'title': 'Login',
        'form': form
    }
    return render(request, 'accounts/login.html', context)

accounts/templates/accounts/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <!-- Custom styles for this template -->
    <link href="{% static "/css/navbar-top-fixed.css" %}" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'accounts:home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

<main class="container">
    <div class="bg-light p-5 rounded">
    </div>
</main>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Custom styles for this template -->
    <link href="{% static "/css/signin.css" %}" rel="stylesheet">
    </head>


    <main class="form-signin text-center">
        <form method="POST">
            {% csrf_token %}
            <img class="mb-4" src="https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="72"
                 height="57">
            <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

            <div class="form-floating">
                <input type="email" name="email" class="form-control" id="floatingInput" placeholder="Email address">
                <label for="floatingInput">Email address</label>
            </div>

            <div class="form-floating">
                <input type="password" name="password" class="form-control" id="floatingPassword"
                       placeholder="Password">
                <label for="floatingPassword">Password</label>
            </div>

            <div class="checkbox mb-3">
                <label>
                    <input type="checkbox" value="remember-me"> Remember me
                </label>
            </div>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-info">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% for field in form %}
                {% for error in field.errors %}
                    <p style="color: red;">{{ error }}</p>
                {% endfor %}
            {% endfor %}

            {% if form.non_field_errors %}
                <div style="color: red;">
                    <p>{{ form.non_field_errors }}</p>
                </div>
            {% endif %}
            <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
            {#            <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>#}
        </form>
        <hr>
        <button class="btn btn-default">
            <a href="{% url 'accounts:register_attempt' %}" class="btn btn-default">Create new account</a>
        </button>
    </main>
{% endblock content %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Custom styles for this template -->
<link href="{% static "/css/signin.css" %}" rel="stylesheet">
</head>


    <main class="form-signin text-center">
        <form method="POST">
            {% csrf_token %}
            <img class="mb-4" src="https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="72"
                 height="57">
            <h1 class="h3 mb-3 fw-normal">Please register</h1>

            <div class="form-floating">
                <input type="text" name="first_name" class="form-control" id="floatingInput" placeholder="First name">
                <label for="floatingInput">First name</label>
            </div>

            <div class="form-floating">
                <input type="text" name="last_name" class="form-control" id="floatingInput" placeholder="Last name">
                <label for="floatingInput">Last name</label>
            </div>

            <div class="form-floating">
                <input type="email" name="email" class="form-control" id="floatingInput" placeholder="Email address">
                <label for="floatingInput">Email address</label>
            </div>
            <div class="form-floating">
                <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
                <label for="floatingPassword">Password</label>
            </div>

            <button class="w-100 btn btn-lg btn-primary" type="submit">Register</button>
            <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
        </form>
    </main>
{% endblock content %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/5.0/dist/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
{% block content %}

{% endblock content %}
<script src="https://getbootstrap.com/docs/5.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>